# Generated by Django 3.2.4 on 2021-06-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covidRecord',
            fields=[
                ('name', models.CharField(default='', max_length=20)),
                ('major', models.CharField(default='', max_length=20)),
                ('student_num', models.CharField(default='', max_length=20)),
                ('phone_num', models.CharField(default='', max_length=15)),
                ('enter_time', models.CharField(default='', max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='historicalRecord',
            fields=[
                ('name', models.CharField(default='', max_length=20)),
                ('major', models.CharField(default='', max_length=20)),
                ('student_num', models.CharField(default='', max_length=20)),
                ('phone_num', models.CharField(default='', max_length=15, primary_key=True, serialize=False)),
                ('reserve_product', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='liveData',
            fields=[
                ('name', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('major', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('student_num', models.CharField(max_length=50)),
                ('phone_num', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('enter_time', models.CharField(default='', max_length=50, null=True)),
                ('reserve_product', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='memberData',
            fields=[
                ('num', models.CharField(default='', max_length=20)),
                ('graduate', models.CharField(default='', max_length=20)),
                ('major', models.CharField(default='', max_length=20)),
                ('student_num', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('phone_num', models.CharField(default='', max_length=15, null=True)),
                ('reserve_product', models.CharField(default='', max_length=10)),
                ('price', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
