# Generated by Django 3.1.6 on 2021-02-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidrecord',
            name='enter_time',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='covidrecord',
            name='phone_num',
            field=models.CharField(default='', max_length=15),
        ),
    ]
