# Generated by Django 2.2.7 on 2021-07-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0003_alter_covidrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidrecord',
            name='major',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='covidrecord',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='major',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='major',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='name',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='major',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='num',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
