# Generated by Django 3.1.7 on 2021-02-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0004_livedata_reserve_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrecord',
            name='reserve_date',
        ),
        migrations.RemoveField(
            model_name='memberdata',
            name='reserve_date',
        ),
    ]
