# Generated by Django 2.2.7 on 2021-07-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0004_auto_20210702_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedata',
            name='email',
            field=models.CharField(default='', max_length=128),
        ),
    ]
