# Generated by Django 3.1.7 on 2021-05-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0005_auto_20210226_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedata',
            name='email',
            field=models.CharField(default='', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='email',
            field=models.CharField(default='', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='phone_num',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='phone_num',
            field=models.CharField(default='', max_length=50),
        ),
    ]
