# Generated by Django 3.1.7 on 2021-05-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0006_auto_20210519_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livedata',
            name='email',
            field=models.CharField(default='', max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
