# Generated by Django 2.2.7 on 2021-07-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0009_remove_memberdata_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdata',
            name='num',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
