# Generated by Django 3.1.7 on 2021-05-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ido', '0009_auto_20210519_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livedata',
            name='email',
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='email',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='historicalrecord',
            name='phone_num',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='phone_num',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
